apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-alb-ingress-controller
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ACCOUNT_ID}:role/kubernetes/alb-ingress-controller"
  name: aws-alb-ingress-controller
  namespace: kube-system