# Ansible Playbook for my Jenkins AMI
# Author: Andrew Jarombek
# Date: 11/5/2018

# Use Ansible's local mode to provision on the machine the playbook is run on
- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Install Java8, Git, Wget & Unzip
      become: yes
      # {{item}} is replaced with each item in "with_items"
      apt: pkg={{item}} state=installed
      # You can think of "with_items" as creating a for loop around this task
      with_items:
        - openjdk-8-jdk
        - git
        - wget
        - unzip

    # Downloading Jenkins - https://jenkins.io/doc/book/installing/#debianubuntu
    - name: Download Jenkins
      become: yes
      # 'command' cares about the returned code from the shell command.
      # Ansible playbook fails if an error is returned.
      command: "{{item}} || /bin/true"
      ignore_errors: True
      with_items:
        - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
        - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update APT Packages
      become: yes
      apt:
        update_cache: yes

    - name: Install Jenkins & NFS
      become: yes
      apt:
        pkg: "{{item}}"
        state: installed
        force: yes
      with_items:
        - jenkins
        - nfs-common

    # Terraform is commonly used by the Jenkins pipeline.  It should be installed on the master agent
    - name: Install Terraform
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
        - unzip terraform_0.11.10_linux_amd64.zip
        - mv terraform /usr/local/bin/
        - terraform --version

    # CloudFormation is commonly used by the Jenkins pipeline and should be on the master agent as well
    - name: Install AWS CLI
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - python --version
        - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        - python get-pip.py
        - pip --version
        - pip install awscli
        - aws --version