# Ansible Playbook for my Jenkins AMI
# Author: Andrew Jarombek
# Date: 11/5/2018

# Use Ansible's local mode to provision on the machine the playbook is run on
- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Install Java8, Python3, Git, Wget & Unzip
      become: yes
      # {{item}} is replaced with each item in "with_items"
      apt: pkg={{item}} state=installed
      # You can think of "with_items" as creating a for loop around this task
      with_items:
        - openjdk-8-jdk
        - git
        - wget
        - unzip
        - software-properties-common

    - name: Add Python3.8 Repository
      apt_repository:
         repo: ppa:deadsnakes/ppa
         state: present

    - name: Update APT Packages
      become: yes
      apt:
        update_cache: yes

    - name: Install Python 3.8
      become: yes
      apt:
        pkg: "{{item}}"
        state: installed
        force: yes
      with_items:
        - python3.8
        - python3-pip
        - python3.8-venv

    # Downloading Jenkins - https://jenkins.io/doc/book/installing/#debianubuntu
    - name: Download Jenkins
      become: yes
      # 'command' cares about the returned code from the shell command.
      # Ansible playbook fails if an error is returned.
      command: "{{item}} || /bin/true"
      ignore_errors: True
      with_items:
        - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
        - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update APT Packages
      become: yes
      apt:
        update_cache: yes

    - name: Install Jenkins & NFS
      become: yes
      apt:
        pkg: "{{item}}"
        state: installed
        force: yes
      with_items:
        - jenkins
        - nfs-common

    # Terraform is commonly used by the Jenkins pipeline.  It should be installed on the master agent
    - name: Install Terraform
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
        - unzip terraform_0.11.11_linux_amd64.zip
        - mv terraform /usr/local/bin/
        - terraform --version

    # CloudFormation is commonly used by the Jenkins pipeline and should be on the master agent as well
    - name: Install AWS CLI
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - python --version
        - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        - python get-pip.py
        - pip --version
        - pip install awscli
        - aws --version

    # Install Node.js for working with JavaScript applications.
    - name: Install Node.js
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
        - bash nodesource_setup.sh
        - apt -y install nodejs
        - npm i yarn -g
        - nodejs --version
        - npm --version
        - yarn --version

    # JQ is used to parse JSON from Bash
    - name: Install jq
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - add-apt-repository ppa:eugenesan/ppa
        - apt-get update
        - apt-get -y install jq