# Kubernetes deployment into the kube-system namespace for the ALB ingress controller.
# Author: Andrew Jarombek
# Date: 6/14/2020

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aws-alb-ingress-controller
  name: aws-alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.4
          args:
            - --ingress-class=alb
            - --cluster-name=andrew-jarombek-eks-cluster
            - --aws-vpc-id=${VPC_ID}
            - --aws-region=us-east-1
      serviceAccountName: aws-alb-ingress-controller
