# Kubernetes deployment for the Jenkins server.
# Author: Andrew Jarombek
# Date: 6/14/2020

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: production
    application: jenkins-server
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      application: jenkins-server
      environment: production
  template:
    metadata:
      labels:
        version: v1.0.0
        environment: production
        application: jenkins-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - development-tests
      containers:
        - name: jenkins-server
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/jenkins-jarombek-io:1.0.0
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
            - mountPath: "/usr/bin/docker"
              name: dockercli
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            httpGet:
              path: /login
              port: 8080
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
            - name: jnlp-port
              containerPort: 50000
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock