# Kubernetes ingress object for the Jenkins server's ALB ingress controller.
# Author: Andrew Jarombek
# Date: 6/14/2020

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: ${ACM_CERT_ARNS}
    alb.ingress.kubernetes.io/subnets: ${SUBNET_IDS}
  labels:
    version: v1.0.0
    environment: production
    application: jenkins-server
spec:
  rules:
    - host: jenkins.jarombek.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: jenkins-service
              servicePort: 80
