# Kubernetes role (in the jenkins namespace) for the Jenkins server.
# Author: Andrew Jarombek
# Date: 6/27/2020

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-server
  namespace: jenkins
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "events"
      - "pods/exec"
      - "pods/log"
    verbs:
      - "get"
      - "watch"
      - "list"