# Kubernetes role binding to a service account for the Jenkins server.
# Author: Andrew Jarombek
# Date: 6/27/2020

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-server
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-server
subjects:
  - kind: ServiceAccount
    name: jenkins-server
    namespace: jenkins