# Kubernetes namespace for Jenkins in the development environment.
# Author: Andrew Jarombek
# Date: 6/14/2020

apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-dev
  labels:
    name: jenkins-dev
    environment: development