# Kubernetes namespace for sandbox applications and prototypes.
# Author: Andrew Jarombek
# Date: 6/14/2020

apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    name: sandbox
    environment: sandbox